# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1542aff9d163b45f0c0085d4663189f20e409cfa1157160c4438a1ed12fbd258f9cd4a1dc8abd513efae37d1c09c8debde5712dd75bc3b5615d2b2f983caef35

test:
  secret_key_base: 7b8cf261fe3faf594614aa0fe0d07b316b6ad30eff6d0ae0a440f86eb504e3a98d75f12ac5fb4da4106e6005c98eb6f14197e84e0e633a2d4de45f3faff3d653

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
